name: Build e Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        run: |
          pip uninstall pygame -y || true
          pip install pygame-ce pygame-gui pyinstaller Pillow
      - name: Compilar Linux
        run: |
          pyinstaller --onefile --windowed \
            --add-data "assets:assets" \
            --add-data "config:config" \
            --add-data "version.json:." \
            --name "SpeedVsLabubu-Linux" \
            main.py
      - name: Upload Release Asset Linux
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SpeedVsLabubu-Linux

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependências
        shell: bash
        run: |
          pip uninstall pygame -y || true
          pip install pygame-ce pygame-gui pyinstaller Pillow
      - name: Compilar Windows
        run: |
          pyinstaller --onefile --windowed `
            --add-data "assets;assets" `
            --add-data "config;config" `
            --add-data "version.json;." `
            --name "SpeedVsLabubu-Windows" `
            main.py
      - name: Upload Release Asset Windows
        uses: softprops/action-gh-release@v2
        with:
          files: dist/SpeedVsLabubu-Windows.exe
